[package]
name = "ebox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "env", "string", "unicode"] }
chrono = "0.4.38"
walkdir = "2.5.0"
ffmpeg-next = { version = "7.1.0" }
rayon = "1.10.0"
tokio = { version = "1.41.1", features = ["full"] }
futures = "0.3.31"
async-openai = { version = "0.26.0", features = ["native-tls", "realtime"] }
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
shellexpand = "3.1.0"
prettytable = "0.10.0"


[[bin]]
name ="vmd"
path = "src/bin/vmd.rs"

[[bin]]
name = "ag"
path = "src/bin/ag.rs"
