name: CI

on:
  push:
    branches:
      - master

jobs:
  check-and-release:
    runs-on: windows-latest
    env:
      FFMPEG_DIR: C:\ProgramData\scoop\apps\ffmpeg-shared\current
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current version
        id: get_version
        run: |
          CURRENT_VERSION=$(grep '^version' Cargo.toml | cut -d '"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get latest tag
        uses: JinoArch/get-latest-tag@latest
        id: tag

      - name: Check if version has changed
        id: check_version_change
        run: |
          LATEST_TAG=${{ steps.tag.outputs.latestTag  }}
          echo "Latest tag is $LATEST_TAG"
          echo "Current version is ${{ steps.get_version.outputs.CURRENT_VERSION }}"
          if [ "$LATEST_VERSION" != "${{ steps.get_version.outputs.CURRENT_VERSION }}" ]; then
              echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
            else
              echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Install deps
        if: ${{ steps.check_version_change.outputs.VERSION_CHANGED == 'true' }}
        uses: winpax/scoop-setup@v1.0.0
        with:
          apps: vcpkg pkg-config llvm ffmpeg-shared

      - name: Add path
        if: ${{ steps.check_version_change.outputs.VERSION_CHANGED == 'true' }}
        run:
          echo "$FFMPEG_DIR\bin" >> $GITHUB_PATH
        shell: bash

      - name: Build binaries
        if: ${{ steps.check_version_change.outputs.VERSION_CHANGED == 'true' }}
        run: |
          mkdir dist
          make DISPATCH_DIR=dist

      - name: Packing
        if: ${{ steps.check_version_change.outputs.VERSION_CHANGED == 'true' }}
        run: |
          7z a ebox_v${{ steps.get_version.outputs.CURRENT_VERSION }}.zip dist/*

      - name: Create Release and upload assets
        if: ${{ steps.check_version_change.outputs.VERSION_CHANGED == 'true' }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.get_version.outputs.CURRENT_VERSION }}"
          name: "v${{ steps.get_version.outputs.CURRENT_VERSION }}"
          files: |
            ebox_v${{ steps.get_version.outputs.CURRENT_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}